services:
  - type: web
    name: ruralshield
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FIELD_ENC_KEY
        sync: false
